// -----------------------------------------------------------------------------
// <auto-generated>
//  this code was generated from a template.
//
//  manual changes to this file may cause unexpected behavior in your app.
//  manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
// -----------------------------------------------------------------------------
import { IAction } from './IActionsFile';

class Gen {
    public indent: string = '';
    private lines: string[] = [];
    private eolPrinted: boolean = false;

    public append(text: string): void {
        if (this.eolPrinted) { this.lines.push(this.indent); }
        this.lines.push(text);
        this.eolPrinted = true;
    }

    public eol(): void {
        if (this.eolPrinted) {
            return;
        }
        this.eolPrinted = true;
        this.lines.push('\n');
    }

    public forceEol(): void {
        this.eolPrinted = true;
        this.lines.push('\n');
    }

    public toString(): string {
        return this.lines.join('');
    }
}

function generate(action: IAction): string {
    const gen = new Gen();
    generateContent(gen, action);
    return gen.toString();
}

function generateContent(gen: any, action: IAction): void {
    const indent = gen.indent;
    gen.append('export const ');
    gen.append((action.typeName).toString());
    gen.append(' = \'');
    gen.append((action.typeContent).toString());
    gen.append('\';');
    gen.eol();
    gen.append('export class ');
    gen.append((action.name).toString());
    gen.append(' implements IAction {');
    gen.eol();
    gen.append('  public type = ');
    gen.append((action.typeName).toString());
    gen.append(';');
    gen.eol();
    gen.append('  function Object() { [native code] }(');
    gen.append((action.parameters).toString());
    gen.append(') { }');
    gen.eol();
    gen.append('}');
}

export const actionGenerator = {
    generate,
    generateContent
};
