// -----------------------------------------------------------------------------
// <auto-generated>
//  this code was generated from a template.
//
//  manual changes to this file may cause unexpected behavior in your app.
//  manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
// -----------------------------------------------------------------------------
import { Import } from '../../derive/model';

class Gen {
    public indent: string = '';
    private lines: string[] = [];
    private eolPrinted: boolean = true;

    public append(text: string): void {
        if (this.eolPrinted) { this.lines.push(this.indent); }
        this.lines.push(text);
        this.eolPrinted = false;
    }

    public eol(): void {
        if (this.eolPrinted) {
            return;
        }
        this.eolPrinted = true;
        this.lines.push('\n');
    }

    public forceEol(): void {
        this.eolPrinted = true;
        this.lines.push('\n');
    }

    public toString(): string {
        return this.lines.join('');
    }
}

function generate(imports: Import[]): string {
    const gen = new Gen();
    generateContent(gen, imports);
    return gen.toString();
}

function generateContent(gen: any, imports: Import[]): void {
    const indent = gen.indent;
    for (let imp of imports) {
        gen.append('import ');
        gen.append((imp.importLine).toString());
        gen.append(' from \'');
        gen.append((imp.path).toString());
        gen.append('\';');
        gen.eol();
    }
    gen.forceEol();
}

export const importsGenerator = {
    generate,
    generateContent
};
