// -----------------------------------------------------------------------------
// <auto-generated>
//  this code was generated from a template.
//
//  manual changes to this file may cause unexpected behavior in your app.
//  manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
// -----------------------------------------------------------------------------
import { ReducerAction, ReducerFile } from '../../../derive/model';

class Gen {
    public indent: string = '';
    private lines: string[] = [];
    private eolPrinted: boolean = true;

    public append(text: string): void {
        if (this.eolPrinted) { this.lines.push(this.indent); }
        this.lines.push(text);
        this.eolPrinted = false;
    }

    public eol(): void {
        if (this.eolPrinted) {
            return;
        }
        this.eolPrinted = true;
        this.lines.push('\n');
    }

    public forceEol(): void {
        this.eolPrinted = true;
        this.lines.push('\n');
    }

    public toString(): string {
        return this.lines.join('');
    }
}

function generate(action: ReducerAction, file: ReducerFile): string {
    const gen = new Gen();
    generateContent(gen, action, file);
    return gen.toString();
}

function generateContent(gen: any, action: ReducerAction, file: ReducerFile): void {
    const indent = gen.indent;
    gen.append('map[actions.');
    gen.append((action.constantName).toString());
    gen.append('] = function(prev: ');
    gen.append((file.stateName).toString());
    gen.append(', action: IAction): ');
    gen.append((file.stateName).toString());
    gen.append(' {');
    gen.eol();
    gen.append('  const a = action as actions.');
    gen.append((action.name).toString());
    gen.append(';');
    gen.eol();
    gen.append('  return ');
    gen.append((action.reductionLine).toString());
    gen.append(';');
    gen.eol();
    gen.append('}');
    gen.eol();
}

export const reducerActionGenerator = {
    generate,
    generateContent
};
