// -----------------------------------------------------------------------------
// <auto-generated>
//  this code was generated from a template.
//
//  manual changes to this file may cause unexpected behavior in your app.
//  manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
// -----------------------------------------------------------------------------
import { ReducerFile } from '../../../derive/model';
import { importsGenerator, disclaimer, isLast } from '..';
import { reducerActionGenerator, childReducerGenerator } from '.';

class Gen {
    public indent: string = '';
    private lines: string[] = [];
    private eolPrinted: boolean = true;

    public append(text: string): void {
        if (this.eolPrinted) { this.lines.push(this.indent); }
        this.lines.push(text);
        this.eolPrinted = false;
    }

    public eol(): void {
        if (this.eolPrinted) {
            return;
        }
        this.eolPrinted = true;
        this.lines.push('\n');
    }

    public forceEol(): void {
        this.eolPrinted = true;
        this.lines.push('\n');
    }

    public toString(): string {
        return this.lines.join('');
    }
}

function generate(file: ReducerFile): string {
    const gen = new Gen();
    generateContent(gen, file);
    return gen.toString();
}

function generateContent(gen: any, file: ReducerFile): void {
    const indent = gen.indent;
    gen.indent = indent + '';
    disclaimer.generateContent(gen);
    gen.indent = indent;
    gen.eol();
    gen.indent = indent + '';
    importsGenerator.generateContent(gen, file.imports);
    gen.indent = indent;
    gen.eol();
    gen.forceEol();
    gen.append('type actor = (prev: ');
    gen.append((file.stateName).toString());
    gen.append(', action: { type: string }) => ');
    gen.append((file.stateName).toString());
    gen.append(';');
    gen.eol();
    gen.append('const map = stringMap<actor>();');
    gen.eol();
    for (let child of file.childReducers) {
        gen.forceEol();
        gen.indent = indent + '';
        childReducerGenerator.generateContent(gen, child, file);
        gen.indent = indent;
        gen.eol();
    }
    for (let action of file.actions) {
        gen.forceEol();
        gen.indent = indent + '';
        reducerActionGenerator.generateContent(gen, action, file);
        gen.indent = indent;
        gen.eol();
    }
    gen.forceEol();
    if (!file.initFields.length) {
        gen.append('export const ');
        gen.append((file.stateName).toString());
        gen.append('Init = init;');
        gen.eol();
    } else {
        gen.append('export function ');
        gen.append((file.stateName).toString());
        gen.append('Init(): ');
        gen.append((file.stateName).toString());
        gen.append(' {');
        gen.eol();
        gen.append('  return {');
        gen.eol();
        for (let field of file.initFields) {
            if (field.isNull) {
                gen.append('     ');
                gen.append((field.field).toString());
                gen.append(': null');
                if (!isLast(field, file.initFields)) {
                    gen.append(',');
                }
                gen.eol();
            } else {
                gen.append('     ');
                gen.append((field.field).toString());
                gen.append(': ');
                gen.append((field.stateName).toString());
                gen.append('Init()');
                if (!isLast(field, file.initFields)) {
                    gen.append(',');
                }
                gen.eol();
            }
        }
        gen.append('  };');
        gen.eol();
        gen.append('}');
        gen.eol();
    }
    gen.forceEol();
    gen.append('export function ');
    gen.append((file.stateName).toString());
    gen.append('Reducer(prev: ');
    gen.append((file.stateName).toString());
    gen.append(' = ');
    gen.append((file.stateName).toString());
    gen.append('Init(), action: { type: string }): ');
    gen.append((file.stateName).toString());
    gen.append(' {');
    gen.eol();
    gen.append('  const specificReducer = map[action.type];');
    gen.eol();
    gen.append('  return (specificReducer && specificReducer(prev, action)) || prev;');
    gen.eol();
    gen.append('}');
    gen.eol();
    gen.forceEol();
    gen.append('export const  ');
    gen.append((file.stateName).toString());
    gen.append('Reduceable = [');
    gen.eol();
    for (let exported of file.exportedActions) {
        gen.append('  ...');
        gen.append((exported).toString());
        if (!isLast(exported, file.exportedActions)) {
            gen.append(',');
        }
        gen.eol();
    }
    gen.append('];');
    gen.eol();
}

export const reducerGenerator = {
    generate,
    generateContent
};
