// -----------------------------------------------------------------------------
// <auto-generated>
//  this code was generated from a template.
//
//  manual changes to this file may cause unexpected behavior in your app.
//  manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
// -----------------------------------------------------------------------------
import { DispatcherFile } from '../../../derive/model';

class Gen {
    public indent: string = '';
    private lines: string[] = [];
    private eolPrinted: boolean = true;

    public append(text: string): void {
        if (this.eolPrinted) { this.lines.push(this.indent); }
        this.lines.push(text);
        this.eolPrinted = false;
    }

    public eol(): void {
        if (this.eolPrinted) {
            return;
        }
        this.eolPrinted = true;
        this.lines.push('\n');
    }

    public forceEol(): void {
        this.eolPrinted = true;
        this.lines.push('\n');
    }

    public toString(): string {
        return this.lines.join('');
    }
}

function generate(file: DispatcherFile): string {
    const gen = new Gen();
    generateContent(gen, file);
    return gen.toString();
}

function generateContent(gen: any, file: DispatcherFile): void {
    const indent = gen.indent;
    gen.forceEol();
    gen.append('getState(): ');
    gen.append((file.stateName).toString());
    gen.append(' {');
    gen.eol();
    gen.append('  return this.service.getState();');
    gen.eol();
    gen.append('}');
    gen.eol();
    gen.forceEol();
    gen.append('subscribe(subscription: (state: ');
    gen.append((file.stateName).toString());
    gen.append(') => void): void {');
    gen.eol();
    gen.append('  this.service.subscribe(subscription);');
    gen.eol();
    gen.append('}');
}

export const directSubscribeGenerator = {
    generate,
    generateContent
};
