// -----------------------------------------------------------------------------
// <auto-generated>
//  this code was generated from a template.
//
//  manual changes to this file may cause unexpected behavior in your app.
//  manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
// -----------------------------------------------------------------------------
import { DispatcherAction, DispatcherFile } from '../../../derive/model';

class Gen {
    public indent: string = '';
    private lines: string[] = [];
    private eolPrinted: boolean = true;

    public append(text: string): void {
        if (this.eolPrinted) { this.lines.push(this.indent); }
        this.lines.push(text);
        this.eolPrinted = false;
    }

    public eol(): void {
        if (this.eolPrinted) {
            return;
        }
        this.eolPrinted = true;
        this.lines.push('\n');
    }

    public forceEol(): void {
        this.eolPrinted = true;
        this.lines.push('\n');
    }

    public toString(): string {
        return this.lines.join('');
    }
}

function generate(action: DispatcherAction, file: DispatcherFile): string {
    const gen = new Gen();
    generateContent(gen, action, file);
    return gen.toString();
}

function generateContent(gen: any, action: DispatcherAction, file: DispatcherFile): void {
    const indent = gen.indent;
}

export const dispatcherActionGenerator = {
    generate,
    generateContent
};
